### ISSUE TITLE
Submodule not published as part of the package

### ISSUE THREAD

**Issue by ming-suhi** [ming-suhi/djs-manager#1]
**Description**
Submodule not published as part of the package. This causes the error shown below.

**Error Message**
```
Error: Cannot find module '@ming-suhi/djs-local-manager-test'
Require stack:
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\63966\Documents\GitHub\djs-test\index.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\63966\\Documents\\GitHub\\djs-test\\index.js' ]
}
```

**Comment by ming-suhi** [comment]
Closed with commit

commit reference: 13ddf585ea8bd9acc4082e3898554cbdd8763668
